import React from 'react';
import Head from 'next/head';
import HeaderInterface from '../interfaces/header';

const Header: React.ComponentType<HeaderInterface> = ({title}) => {
    return(
        <Head>
            <title>{title} Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    )
}

export default Header;